GET https://localhost:9081/resources/test/1
Authorization: Basic admin admin
Accept: application/json

###
POST https://localhost:9081/resources/test/2
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "property": "prova"
}

###

GET https://localhost:9081/resources/test

###
##
# curl -X POST --location "http://localhost:8082/resources/test" -H "Content-Type: application/json" -H "Accept: application/json" -d "{\"property\": \"prova\"}" --basic --user admin:admin
POST https://localhost:9081/resources/test
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "property": "prova"
}
